clc; clear; close all;
n = -10:10; 
xn = exp((-0.1+1i*0.3).*n);
figure;
subplot(2,2,1);
plot(n, abs(xn));
title("Magnitude");
xlabel('n'); ylabel('Magnitude');
subplot(2,2,2);
plot(n, imag(xn));
title("Imaginary Part");
xlabel('n'); ylabel('Imag(x(n))');
subplot(2,2,3);
plot(n, real(xn));
title("Real Part");
xlabel('n'); ylabel('Real(x(n))');
subplot(2,2,4);
plot(n, angle(xn));
title("Phase");
xlabel('n'); ylabel('Phase (radians)');
